In [1]:
import sys
print(sys.executable)

C:\Users\adity\OneDrive\Desktop\All Folders\Git projects\Generative AI and Machine Learning\venv\Scripts\python.exe


In [7]:
import numpy as np

n = np.array([1,2,3,4,5])
z=np.zeros((3,4))
o=np.ones((2,3))
r=np.arange(0,10,2)
l=np.linspace(0,1,5)

print("n = ",n)
print("z = ",z)
print("o = ",o)
print("r = ",r)
print("l = ",l)

n =  [1 2 3 4 5]
z =  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
o =  [[1. 1. 1.]
 [1. 1. 1.]]
r =  [0 2 4 6 8]
l =  [0.   0.25 0.5  0.75 1.  ]


In [11]:
print(n.shape)
print(z.shape)
print(z.ndim)
print(n.dtype)

(5,)
(3, 4)
2
int64
