In [1]:
import sys
print(sys.executable)

C:\Users\adity\OneDrive\Desktop\All Folders\Git projects\Generative AI and Machine Learning\venv\Scripts\python.exe


In [7]:
import numpy as np

n = np.array([1,2,3,4,5])
z=np.zeros((3,4))
o=np.ones((2,3))
r=np.arange(0,10,2)
l=np.linspace(0,1,5)

print("n = ",n)
print("z = ",z)
print("o = ",o)
print("r = ",r)
print("l = ",l)

n =  [1 2 3 4 5]
z =  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
o =  [[1. 1. 1.]
 [1. 1. 1.]]
r =  [0 2 4 6 8]
l =  [0.   0.25 0.5  0.75 1.  ]


In [11]:
print(n.shape)
print(z.shape)
print(z.ndim)
print(n.dtype)

(5,)
(3, 4)
2
int64


In [49]:
# -- Reshaping --------------------------------------------
m = np.arange(12).reshape(3, 4)  # 3 rows, 4 cols
flat = m.flatten()                # 1D version

# -- Statistics -------------------------------------------
data = np.array([10, 20, 30, 40, 50,60])

print(np.mean(data))    # 30.0
print(np.median(data))  # 30.0
print(np.std(data))     # 14.14...
print(np.min(data))     # 10
print(np.max(data))     # 50
print(np.sum(data))     # 150

35.0
35.0
17.07825127659933
10
60
210


In [50]:
# -- Indexing and slicing ----------------------------------
m = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(m[0, :])      # first row: [1 2 3]
print(m[:, 1])      # second column: [2 5 8]
print(m[1:3, 0:2])  # sub-matrix

[1 2 3]
[2 5 8]
[[4 5]
 [7 8]]


In [51]:
# -- Boolean masking --------------------------------------
arr = np.array([5, 15, 25, 35])

mask = arr > 20

print(arr[mask])  # [25 35]

[25 35]


In [54]:
# -- Random numbers ---------------------------------------
np.random.seed(42)          # reproducibility

x = np.random.rand(3, 3)    # uniform distribution in [0, 1)
y = np.random.randn(100)    # standard normal distribution

print(x)
print(y)

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]
[-0.58087813 -0.52516981 -0.57138017 -0.92408284 -2.61254901  0.95036968
  0.81644508 -1.523876   -0.42804606 -0.74240684 -0.7033438  -2.13962066
 -0.62947496  0.59772047  2.55948803  0.39423302  0.12221917 -0.51543566
 -0.60025385  0.94743982  0.291034   -0.63555974 -1.02155219 -0.16175539
 -0.5336488  -0.00552786 -0.22945045  0.38934891 -1.26511911  1.09199226
  2.77831304  1.19363972  0.21863832  0.88176104 -1.00908534 -1.58329421
  0.77370042 -0.53814166 -1.3466781  -0.88059127 -1.1305523   0.13442888
  0.58212279  0.88774846  0.89433233  0.7549978  -0.20716589 -0.62347739
 -1.50815329  1.09964698 -0.17773212 -0.41038331  1.17971634 -0.89820794
  0.83479542  0.29656138 -1.03782988 -0.07580375  0.97296353  0.79559546
  1.49543425  0.33818125  3.37229625 -0.92039081 -0.39863839 -0.06086409
 -1.41875046  1.04249162  0.90353249  0.01900033 -0.53441645 -1.49505387
 -0.78925833  0

In [55]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)       # [5 7 9]
print(a * 2)       # [2 4 6]
print(a ** 2)      # [1 4 9]
print(np.dot(a, b))  # dot product = 32

[5 7 9]
[2 4 6]
[1 4 9]
32


In [56]:
matrix = np.ones((3, 3))

row = np.array([1, 2, 3])  # shape (3,)

result = matrix + row  # adds row to each row of matrix

print(result)
# [[2. 3. 4.]
#  [2. 3. 4.]
#  [2. 3. 4.]]

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
